### ISSUE TITLE
Preview Card doesn't display non-latin characters properly

### ISSUE THREAD

**Issue by oragegu** [bookwyrm-social/bookwyrm#1828]
**Describe the bug**
Preview Card doesn't display non-latin characters properly

**To Reproduce**
1. Follow with a mastodon account the bookwyrm account that is about to publish a review the name of the book non-latin
2. Publish review
3. See the preview card with not-properly-displayed-non-latin-chars

**Expected behavior**
Display preview cards with non-latin book names

**Screenshots**
![image](https://user-images.githubusercontent.com/78921858/149646051-4eac4608-9ca3-49f3-8937-965871bab002.png)

**Instance**
Dans Mon Catalogue: book.dansmonorage.blue

**Comment by mouse-reeve** [comment]
Thank you! Can you link the book? It could be the font, or the character encoding.

**Comment by oragegu** [comment]
link of “wants to read”: https://book.dansmonorage.blue/user/pikapika/generatednote/4180#anchor-4180


Link to the book:
https://book.dansmonorage.blue/book/19137

**Comment by oragegu** [comment]
> Thank you! Can you link the book? It could be the font, or the character encoding.

Just tested with a French book, the accents are properly rendered. Guess in this case the encoding is fine 

![C1F17A0B-09A3-4A60-AF39-095F397F074D](https://user-images.githubusercontent.com/78921858/149658277-309e7cbe-bd0c-4c79-8712-781cf548e5ce.jpeg)

link: https://book.dansmonorage.blue/user/pikapika/generatednote/4230

**Comment by mouse-reeve** [comment]
Thank you! It seems like Open Sans just doesn't support a wide enough range of unicode characters. Based on this person who had a similar issue, we could check is character, or use a different font: https://stackoverflow.com/questions/11411746/drawing-multilingual-text-using-pil/11458418. Either seems doable although the latter is easier code-wise.

@joachimesque do you have an alternate font that you think would look as nice for this that has unicode support? I trust your aesthetic judgment.

**Comment by nycterent** [comment]
i have stumbled on the same issue too: 

https://akmenys.group.lt/file/uodegos/images/previews/covers/15518-2cddb83b-f8eb-4353-888a-a9b1c0160e50.jpg

the book - https://ziurkes.group.lt/book/15518

**Comment by joachimesque** [comment]
Ooooh indeed, that's a problem! I'll check it out this week. Mouse is right, it's due to the unicode range for the font we're using. I may not find a free+nice font with _complete_ unicode coverage, so I may need to code a character unicode range detection with font switch. The free font Noto Sans (+ Noto Sans Simplified/Hong Kong/Traditional/Japanese/Korean) might do the trick. Including a commercial font like Arial Unicode would be perfect for Unicode support, but not for the license, I think?

Noto is released under the OFL license : https://fonts.google.com/noto/specimen/Noto+Sans/about which should be ok for inclusion in the project.

**Comment by cincodenada** [comment]
I did some digging and there's an open Pillow issue that may have some helpful workarounds, specifically there's an example of doing some character detection and switching fonts: https://github.com/python-pillow/Pillow/issues/4808

And while I'm here, just to sync things up: @oragegu posted the following on Matrix, on a casual overview it looks like all three of these are also released under OFL. Thanks to orage for asking around, I think fonts specifically recommended by the folks who would be using them are better yet!
>Hi there people! So for the font problem I have asked around in the sinophone fediverse, and people there have recommanded three fonts dealing with Japanese/Korean/Chinese(Simplified and Traditional) at the same time :
https://github.com/lxgw/LxgwWenKai
https://github.com/adobe-fonts/source-han-sans
https://cjkfonts.io/blog/cjkfonts_allseto

**Comment by joachimesque** [comment]
Thank you for all the info @cincodenada! I hadn't seen the discussion on Matrix, and the font suggestions are pretty solid.

The way PIL works, I don't think I can switch between multiple fonts for each character in a string when using PIL's `multiline_text` and `getsize_multiline`. For that reason, we have to find the most complete Unicode font. Source Han Sans seems to fit the bill. I've got to test it on a sufficiently wide array of books.

Some tests:

![image](https://user-images.githubusercontent.com/1781070/150118781-9d247b73-de0f-4214-92aa-2d5210a23284.png)
![image](https://user-images.githubusercontent.com/1781070/150118797-511a6e8a-3e9d-4794-b5bb-76ec55d21777.png)
![image](https://user-images.githubusercontent.com/1781070/150118808-6e5435ff-c9e2-472f-9941-7243fe5d2381.png)

**Comment by joachimesque** [comment]
So I have identified three strategies:

### Use the most Unicode-complete font available (with compatible license).

[Adobe Source Han Sans](https://github.com/adobe-fonts/source-han-sans) seems to fit the bill for Latin/Greek/Cyrillic + Chinese/Japanese/Korean scripts, but won't be sufficient for Arabic/Hebrew/Brahmic scripts. Adobe Source Han Sans is packaged in a .TTC file, which is very practical for use with PIL.

I have a draft PR showing the use of Source Han Sans: https://github.com/bookwyrm-social/bookwyrm/pull/1848, you can see some result of my testing in my previous message (the PR now handles different font weights).

I identified that the Noto font might be a good candidate, if we can compile one font of each script in a single .TTC file. I opened an issue to ask if that would be feasible: https://github.com/googlefonts/noto-fonts/issues/2217

### Remake the generation system, with the possibility of fallback fonts

The limitation mainly comes from PIL's inability to have fallback fonts. An alternative to PIL would be the generation of a SVG file, which would be turned to JPG with `cairosvg`. I have made no tests, but I expect that the SVG conversion to JPG respect a font rule with many fallback fonts.

Bad news though: text wrapping is Just Not Done in SVG. Perhaps another way of implementing this strategy would be to generate a HTML document, rendered to JPG with a headless browser. It seems a little bit overkill, and possibly could lead to performance issues on some hardware. CairoSVG seems to be smaller.

### Remake the generation system, with a glyph-by-glyph approach

This would be the most troublesome solution IMO. Each character would have to be drawn and positioned separately with the right font. It would complicate things like wrapping long text strings over multiple lines, and would most likely produce a janky result with loads of [keming](https://en.wiktionary.org/wiki/keming) issues.

## Other considerations

The support of multiple scripts will add tens of megabytes to the project. The TTC file for the Source Han Sans collection weighs 38.6 MB.

**Comment by cincodenada** [comment]
Awesome, this is great progress, and a good summary! In short, I agree with your evaluation:
 - Glyph-by-glyph is basically a nonstarter for the reasons you cite
 - SVG seems like a good backup plan - if we could get some sort of text width measurement, we could maybe do manual wrapping without it being _too_ ugly, but it wouldn't be my first choice.

So as for the best-available-font approach: I think Source Han Sans looks really nice overall, and it's a good improvement over current state. The lack of some of the scripts is a drawback here though for sure. If we can compile multiple fonts together (I wonder if we could even combine CJK from Source Han with Noto for the others?) that would be great indeed!

If that doesn't pan out, one alternative might be to switch fonts on a per-image level - if we have multiple fonts, but each has Latin script + (CJK or Arabic or ...), I would think that should cover most use cases? And we should be able to choose based on total glyphs for an image?

As for size, I think we should at least consider options that avoid putting the font files themselves in the repo - there's [Git LFS](https://git-lfs.github.com/) which is supposed to be pretty seamless but requires an additional tool for support, and I haven't actually used it myself. We could also build it into the Docker images, probably, have them download the fonts as part of the build process from some known source (either Adobe/Google's servers, or some source maintained by the project)

**Comment by joachimesque** [comment]
> As for size, I think we should consider options that avoid putting the font files themselves in the repo - there's [Git LFS](https://git-lfs.github.com/) which is supposed to be pretty seamless but requires an additional install for anyone cloning the project, which seems like a notable downside for a distributed project like this.
> 
> As I write this, I'm realizing since everything is in Docker I think we could also just build it into the Docker images? Have them download the fonts as part of the build process from some known source (either Adobe/Google's servers, or some source maintained by the project)? As long as they're early in the process, with Docker's caching they'd only have to be downloaded once basically, especially now that we don't use `--no-cache` in the upgrade process.

That's a very valid point, thank you!

I don't think that the Noto project will compile a collection just for us, so we would have to do it for BookWyrm. The way I envisioned it, I would have added a standalone script, perhaps with a dev-only `bw-dev` command, to create the collection: download all the files and font utils, etc. As the compilation would only be done once or twice in the life of the project (hopefully 🤞), we could perhaps make it part of a different repository, and make the `docker build` action download the latest release tag for that repo? I have no experience for that kind of things.

**Comment by cincodenada** [comment]
> I don't think that the Noto project will compile a collection just for us, so we would have to do it for BookWyrm. The way I envisioned it, I would have added a standalone script, perhaps with a dev-only `bw-dev` command, to create the collection: download all the files and font utils, etc. As the compilation would only be done once or twice in the life of the project (hopefully 🤞), we could perhaps make it part of a different repository, and make the `docker build` action download the latest release tag for that repo? I have no experience for that kind of things.

Oh yeah that's a good point, I hadn't thought about how that would interact with having to compile a font collection, that would rule out just downloading it from elsewhere.

I think having a font-building repo is a reasonable solution, I haven't done release-type things specifically with GitHub before but have with other tools, and I think it would be doable. Another option would be similar, but have the separate repo build a Docker base image that we'd use - I can go into more detail, but basically we'd upload a Docker image with just Python + fonts to a repository, and then reference that instead of `python:3.9` in the Bookwyrm image. 

It looks like the default repository (DockerHub) has a free tier for open-source projects that should suit us fine - there's a limit of 100 pulls/6 hours, but a pull only happens the first time someone builds the project. If we consistently have new people setting up instances every 5 minutes, we'll have much bigger issues to deal with 😄

**Comment by joachimesque** [comment]
> we don't even know if combining fonts is gonna be the way to go for sure

When I get the time I'll check the capabilities of CairoSVG or alternative SVG render libraries. The preview image should be easy enough to transpose to SVG, it's only the matter of text wrapping that might be annoying (especially without JS manipulation)

**Comment by cincodenada** [comment]
Great. And actually, it may be worth figuring out our own source for the fonts in any case, rather than depending on some external URL that we don't control.

I can look at what that repo might look like if that's helpful, it may even be worth getting that figured out and merging #1848, even if we do end up doing something better - it's a relatively simple change, and a significant improvement for CJK-using folks at least.

@mouse-reeve When you have a minute, I'm curious as to your thoughts about a repo for fonts and/or a base Docker image, since it expands the scope of Bookwyrm-as-a-project admin a bit - I'm happy to chat about either of those in  more detail too.

**Comment by mouse-reeve** [comment]
I second getting #1848 to a mergeable state (as long as it's not a huge amount of work, it looks like it just needs some tests updated?) as a stopgap. 

Just to make sure I'm understanding correctly, would using a font repo mean a new repo under this project on Github is effectively the host of the assets? That seems preferable to me over adding another service like Dockerhub to the mix, if just because there's some overhead to keeping track of and getting people the right access to various services.

**Comment by cincodenada** [comment]
> Just to make sure I'm understanding correctly, would using a font repo mean a new repo under this project on Github is effectively the host of the assets? That seems preferable to me over adding another service like Dockerhub to the mix, if just because there's some overhead to keeping track of and getting people the right access to various services.

Yeah, that's a good summary of it, and you're right - for something this simple, it's unnecessary to bring another service into the mix, when a resources-type repo will do basically the same thing.

As for getting #1848 mergeable, I would like to get this font repo set up before we merge too, so that the font file doesn't make it into the main repo. We just need to do the hardest part, picking a name - `bookwyrm-fonts` is obvious, but it might be nice to be able to make it more general in case we have similar distribution needs in the future. Something like `bookwyrm-assets` maybe? I hate naming things, so I'm open to better suggestions if y'all have them 😅

**Comment by cincodenada** [comment]
Also @joachimesque you're the one working on the actual fix here, so if you think a more complete fix will happen soon enough that a stopgap isn't worthwhile, do let us know!

That said, as I said above, I think a font/assets repo is worthwhile for any solution, just so we don't get a URL pulled out from under us unexpectedly.

**Comment by joachimesque** [comment]
I like `bookwyrm-fonts` for the new repo name, it's simple and we can see immediately what we'll be downloading.

I won't have much time in the coming days for the git manipulations you have in mind, please don't hesitate to make whatever you want with #1848.    
It's on my own fork of the repo I don't think it's yet on the main bookwyrm repo, so I guess you could just grab the [diff](https://patch-diff.githubusercontent.com/raw/bookwyrm-social/bookwyrm/pull/1848.diff) for `bookwyrm/preview_images.py` and make a new branch with all the download scripts and everything? And I'll close my PR + delete my branch, so the 38MB file won't be in the main BW repo (I guess?).

The exact font file I used in my PR is **Variable OTC TTF**, available for download on Source Han Sans download page: https://github.com/adobe-fonts/source-han-sans/tree/release#user-content-variable-otcs

**Comment by cincodenada** [comment]
Great, thanks! In that case, I'll plan on pulling a copy of your branch into my fork, rework the font inclusion so the 38MB file doesn't make it in, and then open a PR from there. Thanks for your work on this!

**Comment by joachimesque** [comment]
Follow-up to https://github.com/bookwyrm-social/bookwyrm/issues/1828#issuecomment-1016629389

- Use the most Unicode-complete font available (with compatible license).
    - I'm looking into FontForge and its scripting options to generate a TTC file containing all Noto fonts. We'll have to distribute the package through a specific repo.
- Remake the generation system, with the possibility of fallback fonts
    - Making a SVG and rasterizing it with CairoSVG won't work: CairoSVG has troubles with [complex fonts](https://cairosvg.org/documentation/#text-and-fonts). They have to be installed on the system, and they won't work with right-to-left writing systems (arabic, hebrew…)
    - Using HTML/CSS and a headless browser + `fonts-noto` Debian package (no specific repo needed for install) would be the best way to go in that case: all the fonts would be installed automatically in the image, and the headless browser would be able to render complicated scripts. We could even make a special RTL style for arabic and hebrew books (not sure if RTL is well handled on Bookwyrm right now?)

**Comment by kallekn** [comment]
This issue doesn't seem to have been resolved yet?

<img width="278" alt="Skärmavbild 2024-02-27 kl  09 57 38" src="https://github.com/bookwyrm-social/bookwyrm/assets/130040501/fdcfe212-c4c7-4860-852e-504f880f0701">

https://kirja.casa/user/kallekn/review/24559/s/

**Comment by Minnozz** [comment]
The font that was switched to supports more scripts, but still not all.

Note that font fallback support is now being developed in Pillow: https://github.com/python-pillow/Pillow/pull/6926
