### ISSUE TITLE
Cannot respond to follow request.

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#2236]
### Discussed in https://github.com/bookwyrm-social/bookwyrm/discussions/2233

<div type='discussions-op-text'>

<sup>Originally posted by **nerdteacher** July 17, 2022</sup>
![image](https://user-images.githubusercontent.com/77229429/179404826-ba84bff8-cc6f-41dc-aae3-4fffbdf03d8f.png)

I have this follow request that I cannot respond to, but it always leads to this page (regardless of if I hit "accept" or "deny"). It always goes to this page:

![image](https://user-images.githubusercontent.com/77229429/179404878-af57c5b6-006c-4313-ae84-847b8a52caea.png)

I'm not sure if others have had this issue (I did try searching around) or what might be causing it (e.g., if they decided to cancel their request? not sure). I just can't make it go away, haha.</div>

**Comment by nerdteacher** [comment]
Oh! Sorry for putting it in the wrong place, haha.

Also, I tried searching for the user, and they don't seem to exist (though I can see other people on bookrastinating). So I wonder if it's a result of deleted accounts? Or something of that nature. (Just in case my observations help?)

**Comment by mouse-reeve** [comment]
Oh, if the user is deleted that might explain it -- but it definitely should give you clearer feedback than this

**Comment by mxamber** [comment]
I have a similar issue right now: I sent a follow request from my usual fedi account to my bookwyrm account but it keeps not showing up. If I search for my main account on bookworm, it finds other users from my main instance, but not my profile itself.

**Comment by mouse-reeve** [comment]
> I have a similar issue right now: I sent a follow request from my usual fedi account to my bookwyrm account but it keeps not showing up. If I search for my main account on bookworm, it finds other users from my main instance, but not my profile itself.

The PR I opened should fix the issue as originally described, but this sounds like a different issue. I saw the other issue you opened, which looks like it stems from the same bug, so I'll proceed with looking into that, and thank you for being patient with the jankiness.

**Comment by nerdteacher** [comment]
Sorry to re-open this thread after so long and right before posting another bug issue, but I noticed that I still see requests that I can't... get rid of that are associated with accounts that don't exist. (I can't delete/reject them.)

I still see the one in the original screenshot, but it's only when I have other new requests to deal with. I'm pretty sure it's associated with deleted accounts, since I have a second one that I can't interact with (gives me an error saying the page doesn't exist) that I know is from someone who deleted their account.

**Comment by mouse-reeve** [comment]
That sounds like an unrelated but very legit bug! I'm going to open a new ticket for it

**Comment by mouse-reeve** [comment]
Can you link me to a user account this is happening with?

**Comment by mouse-reeve** [comment]
Closing this because it's very old
