### ISSUE TITLE
account migration

### ISSUE THREAD

**Issue by prolibre** [bookwyrm-social/bookwyrm#3225]
I saw that bookwyrm.social (message from @mouse-reeve) had blocked the import/export of accounts (account migration). So I guess there is a problem with that.
To be quick, I deleted the links directly from my templates/preferences/layout.html 

but what do you recommend for instance administrators ?

Have a nice day,

Anthony

**Comment by hughrun** [comment]
There will be an update for this shortly.

**Comment by mouse-reeve** [comment]
This is addressed in the new [0.7.2 release](https://github.com/bookwyrm-social/bookwyrm/releases/tag/v0.7.2) -- I recommend upgrading and making sure to update your nginx configuration (explained in the release notes)

**Comment by symac** [comment]
@mouse-reeve I see on https://bookwyrm.social/preferences/user-export that I still can't export my account, is there any reason since this fix seems to address the issue, or is this just something forgotten on bw.social or something else? 

Thanks

**Comment by symac** [comment]
@mirenbz 2 weeks ago @mouse-reeve said on https://github.com/bookwyrm-social/bookwyrm/issues/3580#issuecomment-2899532823 that some progress had been done but there were still things to do before reenabling it on .social.

**Comment by hughrun** [comment]
Mouse found a failure scenario our automated testing didn't pick up, and we've subsequently identified another more significant bug that I'm expecting should be straightforward to fix and test — just haven't had the time to do that. Hopefully this weekend.
