### ISSUE TITLE
Still can't follow from Mastodon

### ISSUE THREAD

**Issue by eishiya** [bookwyrm-social/bookwyrm#3280]
I am still experiencing the same problem as #2545 and #2734: When I attempt to follow my Bookwyrm account from my Mastodon account, Mastodon thinks the follow request has not yet been approved, while no follow request appears on Bookwyrm. I have "manually approve followers" disabled.

**To reproduce**
Try to follow https://books.theunseen.city/user/eishiya from mastodon.ART
On Mastodon, the "Follow" button turns into a "Cancel Follow" button, which usually appears when a follow request has been sent.
On Bookwyrm, no follow request appears, and the follower list is not updated - the follow seems to have completely vaporised.

**Expectation**
The follow goes through automatically (or, if the account has "manually approve followers" enabled, a follow request appears), and the follower list on Bookwyrm is updated.

**Instance**
Bookwyrm: https://books.theunseen.city, which is running version 0.6.6
Mastodon: https://mastodon.art, v4.2.5

**Additional context**
Mastodon.ART uses authorized fetch, perhaps it's related to that?

**Comment by skobkin** [comment]
Did you try the same from another instance?

Mastodon.art is somewhat famous for their defederation with almost everything, so it's not impossible that there's no federation with your bookwyrm instance or your account could be suspended there.

I've tried to follow your account from mine on lor.sh. No problems there.

Also it could be useful to get in contact with your Bookwyrm instance admin and ask them for logs if you know the precise time when you tried to follow. If there was something strange like errors they can see that. This data could be very useful if it's really a Bookwyrm problem.

**Comment by eishiya** [comment]
I do not have other Mastodon or Bookwyrm account to try with. Thanks for checking for me, I do see your follow as normal, so presumably this is something about .ART's config causing problems.

My Bookwyrm instance is not blocked or limited by .ART, and the account is not suspended there, it shows up normally. The authorized fetch thing is the only thing I can think of, and it's .ART's admin's theory as well: https://mastodon.art/@welshpixie/111891429205948907
Another user in that same thread, who is on a different Mastodon instance, mentioned having this issue and that following from Bookwyrm first helped. I tried to test this, but looking up my Mastodon account on Bookwyrm pops up a "server error" message consistently (looking up accounts on other instances seems fine). Perhaps the Bookwyrm instance is trying to fetch data from .ART when I look up my account, and failing.

I will attempt to contact my Bookwyrm instance admin about this.

**Comment by fofwisdom** [comment]
![image](https://github.com/bookwyrm-social/bookwyrm/assets/205521/41889f2f-e63f-4754-bfa4-24f3a8932332)

![image](https://github.com/bookwyrm-social/bookwyrm/assets/205521/93a2e530-3aa1-4bb9-a2ab-8bc9664686fc)

@eishiya I sent you a request from each of your BookWyrm and Mastodon accounts.

Now, if you could take a screenshot showing only one of the requests, it would be easier for others to understand.

**Comment by eishiya** [comment]
I don't understand what you mean by "sent you as request from each of your BookWyrm and Mastodon accounts"? Do you mean you followed from *your* BookWyrm and Mastodon accounts? Because I do see two new follows (not follow requests), are these you?
![image](https://github.com/bookwyrm-social/bookwyrm/assets/70545646/2227a4c0-70dc-469f-b456-3f57fc1fdf58)

One of these is from Mastodon, one appears to be your BookWyrm. The Mastodon one is from mastodon.social, which has been shown to work fine with BookWyrm in the past, and does not use authorized_fetch.

**Comment by fofwisdom** [comment]
Accounts that followed you.

- fow@netsphere.one
- fow@reads.netsphere.pub

![image](https://github.com/bookwyrm-social/bookwyrm/assets/205521/b8e1cd4e-b000-4ac1-9e5b-ae5c00b0b84d)

![image](https://github.com/bookwyrm-social/bookwyrm/assets/205521/0dcdc3e6-ba35-44b5-bedf-11f33306f0ef)

  Both accounts are marked as awaiting your approval.

  "Manually approve followers" feature of BookWyrm doesn't seem to be working properly.

**Comment by eishiya** [comment]
I have "manually approve followers" turned OFF, so the fact that even on BookWyrm you're still seeing it as a follow request is definitely strange. It's just a regular follow on my end.

I see no follow or follow request from your Mastodon account on netsphere.one, so I guess that answers your initial request :D

**Comment by skobkin** [comment]
These "Follow requests" when follow approval is not required on the receiving side are reminding me about Mastodon->Pixelfed follow problem which one of our instance users experiences.

**Comment by msub2** [comment]
As this affects my instance I definitely want to get this figured out. I'm going to spin up a test Mastodon instance with authorized fetch on so I can troubleshoot on both ends, hopefully that'll shed some light on this.

**Comment by hughrun** [comment]
This is extremely likely to be related to "authorized fetch"/"secure mode". Would love to know what you find, @msub2 as we keep thinking we've fixed this and then it pops up again.

**Comment by CactiChameleon9** [comment]
I am having this problem (running my own bookwyrm and mastodon server on public urls).

But also (could be related) bookwyrm -> mastodon DMs work but mastodon -> bookwyrm DMs do not.

Bookwyrm is installed dockerlessly.

**Comment by quisquous** [comment]
Just wanted to follow up that I am still having this issue on following books.theunseen.city (bookwyrm 0.8.1, @msub2's instance) from weirder.earth (v4.2.17+hometown-1.1.2, which also has AUTHORIZED_FETCH turned on). I can search for posts directly on weirder.earth and have them federate but the weirder.earth follow is lost in perpetual "cancel follow" mode with no follow ever seen on the books.theunseen.city side, as the OP describes.

**Comment by hughrun** [comment]
If @msub2 is able to provide some logs either here or privately that will help to troubleshoot this.
